name: entahlah
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  draggable_bottom_sheet: ^1.0.2
  flutter:
    sdk: flutter
  flutter_lyric: ^2.0.4+6
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  just_audio: ^0.9.39
  kana_kit: ^2.0.0
  palette_generator: ^0.3.3+4
  scrollable_positioned_list: ^0.3.8
  spotify: ^0.13.7
  youtube_explode_dart: ^2.2.1
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.3+1
  path: ^1.8.2    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/